### ISSUE TITLE
Android的使用时长统计有问题，和ios相差特别多，应该是Android的这一块实现存在问题

### ISSUE THREAD

**Issue by zhancheng** [ygmpkk/flutter_umplus#1]
首先非常感谢您提供的插件

**Comment by ygmpkk** [comment]
这个问题我也发现了，和Flutter组件initState和dispose有关，友盟的统计必须是严格配对的，实际上组件的生命周期是没有配对的

**Comment by sintrb** [comment]
可以看下这个，对flutter生命周期做了简单扩展，#2

**Comment by rockingdice** [comment]
@sintrb 有没有更好的方法，可以不用对每个page复制粘贴这一大段代码呢？感觉太臃肿了…不知道dart有没有什么语言特性可以做到？

**Comment by sintrb** [comment]
> @sintrb 有没有更好的方法，可以不用对每个page复制粘贴这一大段代码呢？感觉太臃肿了…不知道dart有没有什么语言特性可以做到？

写个page的基类张贴这堆代码，其他的page通过继承呀。。。面向对象编程。

**Comment by ygmpkk** [comment]
> @sintrb 有没有更好的方法，可以不用对每个page复制粘贴这一大段代码呢？感觉太臃肿了…不知道dart有没有什么语言特性可以做到？

是的，手工埋点是挺烦的，最近也在探索全埋点方案

**Comment by rockingdice** [comment]
@sintrb 我自己实现了，不过目前发现这么处理不是特别好。放到每个state里，如果state不释放页面就不会触发进入、退出页面。

比如我希望缓存一些页面的滚动位置，就会把页面的state缓存下来不让它释放；如果app的tab用了类似IndexedStack这种的控件，切换显示也是不会触发的。

目前还没什么好的思路。

**Comment by timer-cp** [comment]
友盟这个坑货，官方插件太烂了。我写了个插件<a href="https://pub.flutter-io.cn/packages/umeng_statistics"> umeng_statistics</a>，统计准确，完美解决。

**Comment by rockingdice** [comment]
@timer-cp 回头我试试 多谢
